### ISSUE TITLE
cant delete temp directory at windows slave

### ISSUE THREAD

**Issue by mavlyutov** [allure-framework/allure-jenkins-plugin#21]
<pre>
Allure Report Generation: started
Allure Report Generation: find directories by mask [test_results/reports/_allure/]
Allure Report Generation: found allure result directories [\cygdrive\c\start\workspace\14.10_smoke_win_all\label\yabrowser-win7-ultimate-x64-ru\test_results\reports\_allure]
Allure Report Generation: copy founded directories in directory [/cygdrive/c/start/workspace/14.10_smoke_win_all/label/yabrowser-win7-ultimate-x64-ru/allure44038899178249473.tmp/results]
Allure Report Generation: generate report from directory [/cygdrive/c/start/workspace/14.10_smoke_win_all/label/yabrowser-win7-ultimate-x64-ru/allure44038899178249473.tmp]
Allure Report Generation: attach report link to build and project
Allure Report Generation: Can't delete directory [/cygdrive/c/start/workspace/14.10_smoke_win_all/label/yabrowser-win7-ultimate-x64-ru/allure44038899178249473.tmp]
java.io.IOException: remote file operation failed: /cygdrive/c/start/workspace/14.10_smoke_win_all/label/yabrowser-win7-ultimate-x64-ru/allure44038899178249473.tmp at hudson.remoting.Channel@5aae89e5:yabrowser-win7-ultimate-x64-ru-536
	at hudson.FilePath.act(FilePath.java:916)
	at hudson.FilePath.act(FilePath.java:893)
	at hudson.FilePath.deleteContents(FilePath.java:1095)
	at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.deleteRecursive(AllureReportPublisher.java:215)
	at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.perform(AllureReportPublisher.java:137)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:756)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:720)
	at hudson.model.Build$BuildExecution.post2(Build.java:182)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:669)
	at hudson.model.Run.execute(Run.java:1731)
	at hudson.matrix.MatrixRun.run(MatrixRun.java:146)
	at hudson.model.ResourceController.execute(ResourceController.java:88)
	at hudson.model.Executor.run(Executor.java:232)
Caused by: java.nio.file.FileSystemException: \cygdrive\c\start\workspace\14.10_smoke_win_all\label\yabrowser-win7-ultimate-x64-ru\allure44038899178249473.tmp\repositories\com\fasterxml\jackson\core\jackson-annotations\2.3.0\jackson-annotations-2.3.0.jar: Процесс не может получить доступ к файлу, так как этот файл занят другим процессом.

	at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
	at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at sun.nio.fs.WindowsFileSystemProvider.implDelete(Unknown Source)
	at sun.nio.fs.AbstractFileSystemProvider.delete(Unknown Source)
	at java.nio.file.Files.delete(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at hudson.Util.deleteFile(Util.java:238)
	at hudson.Util.deleteRecursive(Util.java:301)
	at hudson.Util.deleteContentsRecursive(Util.java:203)
	at hudson.Util.deleteRecursive(Util.java:292)
	at hudson.Util.deleteContentsRecursive(Util.java:203)
	at hudson.Util.deleteRecursive(Util.java:292)
	at hudson.Util.deleteContentsRecursive(Util.java:203)
	at hudson.Util.deleteRecursive(Util.java:292)
	at hudson.Util.deleteContentsRecursive(Util.java:203)
	at hudson.Util.deleteRecursive(Util.java:292)
	at hudson.Util.deleteContentsRecursive(Util.java:203)
	at hudson.Util.deleteRecursive(Util.java:292)
	at hudson.Util.deleteContentsRecursive(Util.java:203)
	at hudson.Util.deleteRecursive(Util.java:292)
	at hudson.Util.deleteContentsRecursive(Util.java:203)
	at hudson.Util.deleteRecursive(Util.java:292)
	at hudson.Util.deleteContentsRecursive(Util.java:203)
	at hudson.FilePath$13.invoke(FilePath.java:1098)
	at hudson.FilePath$13.invoke(FilePath.java:1095)
	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:2474)
	at hudson.remoting.UserRequest.perform(UserRequest.java:118)
	at hudson.remoting.UserRequest.perform(UserRequest.java:48)
	at hudson.remoting.Request$2.run(Request.java:328)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at hudson.remoting.Engine$1$1.run(Engine.java:63)
	at java.lang.Thread.run(Unknown Source)
Allure Report Generation: completed
</pre>

**Comment by baev** [comment]
I guess we can close this one. Feels free to reopen
