### ISSUE TITLE
How to generate report with internal maven repository?

### ISSUE THREAD

**Issue by clicman** [allure-framework/allure-jenkins-plugin#50]
My environment compleltely isolated from the internet. But I have artifactory instance in internal network. How to point report builder to fetch artifacts from this repository url? 

For now it fails with NPE
```
Allure Report Generation: started
Allure Report Generation: find directories by mask [target\allure-results]
Allure Report Generation: found allure result directories [D:\Jenkins\workspace\prj\target\allure-results]
Allure Report Generation: copy founded directories in directory [D:\Jenkins\workspace\prj\allure1008803587963066652.tmp\results]
Allure Report Generation: generate report from directory [D:\Jenkins\workspace\prj\allure1008803587963066652.tmp]
Allure Report Generation: proxy settings [active:'false', host:'null', port:'0', username:'null', password: '']
ERROR: Publisher ru.yandex.qatools.allure.jenkins.AllureReportPublisher aborted due to exception
java.io.IOException: ru.yandex.qatools.allure.report.AllureReportBuilderException: java.lang.NullPointerException
        at ru.yandex.qatools.allure.jenkins.utils.ReportGenerator.invoke(ReportGenerator.java:50)
        at ru.yandex.qatools.allure.jenkins.utils.ReportGenerator.invoke(ReportGenerator.java:25)
        at hudson.FilePath.act(FilePath.java:917)
        at hudson.FilePath.act(FilePath.java:895)
        at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.generateReport(AllureReportPublisher.java:243)
        at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.perform(AllureReportPublisher.java:144)
        at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
        at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:770)
        at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:734)
        at hudson.maven.MavenModuleSetBuild$MavenModuleSetBuildExecution.post2(MavenModuleSetBuild.java:1040)
        at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:683)
        at hudson.model.Run.execute(Run.java:1765)
        at hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:529)
        at hudson.model.ResourceController.execute(ResourceController.java:89)
        at hudson.model.Executor.run(Executor.java:240)
Caused by: ru.yandex.qatools.allure.report.AllureReportBuilderException: java.lang.NullPointerException
        at ru.yandex.qatools.allure.report.AllureReportBuilder.processResults(AllureReportBuilder.java:133)
        at ru.yandex.qatools.allure.jenkins.utils.ReportGenerator.invoke(ReportGenerator.java:47)
        ... 14 more
Caused by: java.lang.NullPointerException
        at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:361)
        at ru.yandex.qatools.clay.Aether.resolveWithTransitives(Aether.java:177)
        at ru.yandex.qatools.clay.Aether.resolve(Aether.java:131)
        at ru.yandex.qatools.clay.Aether.resolve(Aether.java:109)
        at ru.yandex.qatools.allure.report.AllureReportBuilder.processResults(AllureReportBuilder.java:127)
        ... 15 more
Finished: FAILURE
```

**Comment by vania-pooh** [comment]
@clicman you can use ~/.m2/settings.xml file in the same way as you're doing with Maven. Jenkins plugin is also searching for this file.

**Comment by clicman** [comment]
@vania-pooh unfortunately it is not so. I`ve put .m2 with settings.xml in almost all places I can suppose. And another thing... maven project itself resolves settings.xml clearly. I think it must be something else in confuguration or some kind if defect.
P.S. Jenkins running on Windows Server OS.

**Comment by vania-pooh** [comment]
@smecsia, @eroshenkoam any ideas?

**Comment by eroshenkoam** [comment]
https://github.com/jenkinsci/allure-plugin/issues/11
