### ISSUE TITLE
Не удается сгенерировать отчеты

### ISSUE THREAD

**Issue by OlgilvieMaurice** [allure-framework/allure-jenkins-plugin#51]
Проблема чем-то похожа на #15. Локально, с помощью CLI, все генерируется. В Дженкинсе -- валится. Плагин v2.5.
Запускаю тесты: `python3.4 -m pytest --alluredir=allure-results`
Папка allure-results на месте.

	Allure Report Generation: started
	Allure Report Generation: find directories by mask [**/allure-results]
	ERROR: Publisher ru.yandex.qatools.allure.jenkins.AllureReportPublisher aborted due to exception
	java.io.IOException: remote file operation failed: /var/www/bizaccount/bizaccout-ui-tests at hudson.remoting.Channel@7343425d:Bizaccount.test.account.m1.nato: java.io.IOException: Remote call on Bizaccount.test.account.m1.nato failed
		at hudson.FilePath.act(FilePath.java:985)
		at hudson.FilePath.act(FilePath.java:967)
		at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.perform(AllureReportPublisher.java:123)
		at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
		at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:761)
		at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:721)
		at hudson.model.Build$BuildExecution.post2(Build.java:183)
		at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:670)
		at hudson.model.Run.execute(Run.java:1743)
		at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
		at hudson.model.ResourceController.execute(ResourceController.java:89)
		at hudson.model.Executor.run(Executor.java:240)
	Caused by: java.io.IOException: Remote call on Bizaccount.test.account.m1.nato failed
		at hudson.remoting.Channel.call(Channel.java:760)
		at hudson.FilePath.act(FilePath.java:978)
		... 11 more
	Caused by: java.lang.ClassFormatError: Failed to load ru.yandex.qatools.allure.jenkins.utils.GlobDirectoryFinder
		at hudson.remoting.RemoteClassLoader.loadClassFile(RemoteClassLoader.java:325)
		at hudson.remoting.RemoteClassLoader.findClass(RemoteClassLoader.java:237)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:323)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:268)
		at java.lang.Class.forName0(Native Method)
		at java.lang.Class.forName(Class.java:274)
		at hudson.remoting.MultiClassLoaderSerializer$Input.resolveClass(MultiClassLoaderSerializer.java:113)
		at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1611)
		at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1516)
		at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1770)
		at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1349)
		at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1989)
		at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1914)
		at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1797)
		at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1349)
		at java.io.ObjectInputStream.readObject(ObjectInputStream.java:369)
		at hudson.remoting.UserRequest.deserialize(UserRequest.java:185)
		at hudson.remoting.UserRequest.perform(UserRequest.java:99)
		at hudson.remoting.UserRequest.perform(UserRequest.java:49)
		at hudson.remoting.Request$2.run(Request.java:324)
		at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
		at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
		at java.util.concurrent.FutureTask.run(FutureTask.java:166)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1146)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
		at java.lang.Thread.run(Thread.java:701)
		at ......remote call to Bizaccount.test.account.m1.nato(Native Method)
		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1356)
		at hudson.remoting.UserResponse.retrieve(UserRequest.java:221)
		at hudson.remoting.Channel.call(Channel.java:752)
		... 12 more
	Caused by: java.lang.UnsupportedClassVersionError: ru/yandex/qatools/allure/jenkins/utils/GlobDirectoryFinder : Unsupported major.minor version 51.0
		at java.lang.ClassLoader.defineClass1(Native Method)
		at java.lang.ClassLoader.defineClass(ClassLoader.java:643)
		at java.lang.ClassLoader.defineClass(ClassLoader.java:489)
		at hudson.remoting.RemoteClassLoader.loadClassFile(RemoteClassLoader.java:323)
		at hudson.remoting.RemoteClassLoader.findClass(RemoteClassLoader.java:237)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:323)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:268)
		at java.lang.Class.forName0(Native Method)
		at java.lang.Class.forName(Class.java:274)
		at hudson.remoting.MultiClassLoaderSerializer$Input.resolveClass(MultiClassLoaderSerializer.java:113)
		at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1611)
		at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1516)
		at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1770)
		at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1349)
		at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1989)
		at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1914)
		at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1797)
		at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1349)
		at java.io.ObjectInputStream.readObject(ObjectInputStream.java:369)
		at hudson.remoting.UserRequest.deserialize(UserRequest.java:185)
		at hudson.remoting.UserRequest.perform(UserRequest.java:99)
		at hudson.remoting.UserRequest.perform(UserRequest.java:49)
		at hudson.remoting.Request$2.run(Request.java:324)
		at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
		at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
		at java.util.concurrent.FutureTask.run(FutureTask.java:166)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1146)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
		at java.lang.Thread.run(Thread.java:701)

**Comment by eroshenkoam** [comment]
Привет. Вам нужно поставить на агент 7 джаву. 
Проблема исправится.

**Comment by OlgilvieMaurice** [comment]
Спасибо.
