### ISSUE TITLE
Jenkins 1.610 (OpenJDK 1.6): Cannot install plugin (Unsupported major.minor version 51.0)

### ISSUE THREAD

**Issue by elhe** [allure-framework/allure-jenkins-plugin#52]
I try to install plugin for Jenkins with OpenJDK 1.6 using standard plugin manager
When Jenkins restarts  I see no installed plugin
```     
java version "1.6.0_34"
OpenJDK Runtime Environment (IcedTea6 1.13.6) (6b34-1.13.6-1ubuntu0.12.04.1) 
OpenJDK 64-Bit Server VM (build 23.25-b01, mixed mode)
```
Stacktrace from Jenkins log:
```
Apr 23, 2015 11:41:54 AM SEVERE jenkins.InitReactorRunner$1 onTaskFailed
Failed Loading plugin allure-jenkins-plugin
java.io.IOException: Unable to load ru.yandex.qatools.allure.jenkins.AllureReportPlugin from allure-jenkins-plugin
	at hudson.ClassicPluginStrategy.load(ClassicPluginStrategy.java:422)
	at hudson.PluginManager$2$1$1.run(PluginManager.java:370)
	at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:282)
	at jenkins.model.Jenkins$7.runTask(Jenkins.java:904)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:210)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1146)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:701)
Caused by: java.lang.UnsupportedClassVersionError: ru/yandex/qatools/allure/jenkins/AllureReportPlugin : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:643)
	at org.apache.tools.ant.AntClassLoader.defineClassFromData(AntClassLoader.java:1128)
	at org.apache.tools.ant.AntClassLoader.getClassFromStream(AntClassLoader.java:1299)
	at org.apache.tools.ant.AntClassLoader.findClassInComponents(AntClassLoader.java:1355)
	at org.apache.tools.ant.AntClassLoader.findClass(AntClassLoader.java:1315)
	at org.apache.tools.ant.AntClassLoader.loadClass(AntClassLoader.java:1074)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:268)
	at hudson.ClassicPluginStrategy.load(ClassicPluginStrategy.java:415)
	... 9 more
```
I have no problem with OpenJDK 1.7.0_65

**Comment by vania-pooh** [comment]
Yes, that's an expected behavior as we compile Allure with Java 7.

**Comment by elhe** [comment]
thank you. Could you add this information on wiki page? (I think it would save time to others)

**Comment by vania-pooh** [comment]
https://github.com/allure-framework/allure-core/wiki/FAQ-and-Troubleshooting#unsupported-majorminor-version-510 how about this one?

**Comment by elhe** [comment]
ok, thank you
