### ISSUE TITLE
gen report fail:Failed to extract tar archive

### ISSUE THREAD

**Issue by wuhuizuo** [allure-framework/allure-jenkins-plugin#53]
- Jenkins ver: `1.610`
- allure plugin ver:`2.6`
- the exception:
```
Allure Report Generation: started
Allure Report Generation: find directories by mask [**/rspec_reports]
Allure Report Generation: found allure result directories [/jenkins/workspace/VMP4.0_BDD_Testing/src/rspec_reports]
Allure Report Generation: copy founded directories in directory [/jenkins/workspace/VMP4.0_BDD_Testing/allure4934002028448897885.tmp/results]
Allure Report Generation: generate report from directory [/jenkins/workspace/VMP4.0_BDD_Testing/allure4934002028448897885.tmp]
Allure Report Generation: proxy settings [active:'false', host:'null', port:'0', username:'null', password: '']
ERROR: Publisher ru.yandex.qatools.allure.jenkins.AllureReportPublisher aborted due to exception
java.io.IOException: Failed to extract /jenkins/workspace/VMP4.0_BDD_Testing/allure4934002028448897885.tmp/report/**/*
	at hudson.FilePath.readFromTar(FilePath.java:2299)
	at hudson.FilePath.copyRecursiveTo(FilePath.java:2208)
	at hudson.FilePath.copyRecursiveTo(FilePath.java:2112)
	at hudson.FilePath.copyRecursiveTo(FilePath.java:2095)
	at hudson.FilePath.copyRecursiveTo(FilePath.java:2080)
	at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.generateReport(AllureReportPublisher.java:267)
	at ru.yandex.qatools.allure.jenkins.AllureReportPublisher.perform(AllureReportPublisher.java:146)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:761)
at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:721)
	at hudson.model.Build$BuildExecution.post2(Build.java:183)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuildExecution.post(AbstractBuild.java:670)
	at hudson.model.Run.execute(Run.java:1766)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:374)
Caused by: java.io.IOException: Truncated TAR archive
	at org.apache.commons.compress.archivers.tar.TarArchiveInputStream.read(TarArchiveInputStream.java:614)
	at java.io.InputStream.read(InputStream.java:101)
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1792)
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1769)
	at org.apache.commons.io.IOUtils.copy(IOUtils.java:1744)
	at hudson.util.IOUtils.copy((IOUtils.java:40)
	at hudson.FilePath.readFromTar(FilePath.java:2289)
	... 15 more
```

**Comment by vania-pooh** [comment]
@wuhuizuo could you also specify your operating system (some issues are specific to Windows)?

**Comment by wuhuizuo** [comment]
@vania-pooh 
OS info:
3.2.0-4-amd64 #1 SMP Debian 3.2.65-1+deb7u1 x86_64 GNU/Linux

**Comment by vania-pooh** [comment]
Seems to be Jenkins issue https://issues.jenkins-ci.org/browse/JENKINS-28013

**Comment by wuhuizuo** [comment]
@vania-pooh some project gen report successfully(same slave node). and some time this project gen reports ok.

**Comment by wuhuizuo** [comment]
let me upgrade the jenkins to `1.6.11`, then check the issue again.

**Comment by wuhuizuo** [comment]
gen report ok when jenkins upgrade to `1.6.11`
